extends: eslint-config-dmitmel/presets/node
env:
  browser: true
parserOptions:
  sourceType: module

rules:
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: functions
      allow:
        - name
        - length
        - location
        - self
        - status
        - event
        - hasOwnProperty

  func-names: off

  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
        - dynamicImport

overrides:
  - files: '**/*.ts'
    extends: eslint-config-dmitmel/presets/typescript-with-type-checking-addon
    rules:
      node/no-missing-import: off
      '@typescript-eslint/no-namespace': off

  - files: '**/*.d.ts'
    rules:
      no-var: off

  - files: 'src/**/*.ts'
    parserOptions:
      project: tsconfig.json

  - files: 'runtime/src/**/*.ts'
    parserOptions:
      project: runtime/tsconfig.json
