language: node_js
node_js: node

cache:
  yarn: true

install:
  - yarn install

script:
  - yarn run build && yarn run lint && yarn run check-fmt

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
